language: node_js
node_js:
- '4'
- '5'
- '6'
- '7'
- '8'
- node

os:
- linux
- osx

git:
  depth: 1

env:
  global:
    secure: dHZkfjL0eagnG2UBm4cR3DVFgwyPAc4gr48sBfIPrdee6Zm3uz9ctQcSjTmKtOKKQd0g4BNMTgvpi44JuZX79N67fygWmWMCSKSPInkSsnPJLOVArhC0F+T8Eei19hwaARwFZ++MCmsIUoyFtjLsCaG4tO+6jM1uu/0FXDwL//XcYZefMRLMzGv1j3RLJk9dQfY6InilCEqjvcbMlktNbECJs04GVWSl3RsYTffHYUft+0qrwKKA+eDKLCf3qC5hJ6TLW0foF+fNu16jh/gZtw94b8dhpdEqd9gO0bXz4/jt+sI+ubczio0IX1EdG2WLFJxPQvVNz38Bqof1fBe3hesL64rsr3PFuCPs8kdMIHHkKoDLfRS/K/3+PW25XteHkFOEi8UJg6BB5sw1zDhqKc42gybMDphYOIkUkdoNMbUmFJKJy01pP7jqP45ye0sXL0Gff3YPZGfVry7gK+Bh63esQEaCnPrScrdpB8ycKW+KS+ddv6KWUNdQKSHsEWtikQ505WYHtqZ81XIMP6HXLV3H/lMRfT43NOALUBpauuJ+JXM5f1yl8rSJHY0YoA2CUScmUrgJLQ5KsBdRPq5GXS7TKTuRZ7O7J/yWoAys2ok8BOAiq5sths+oZ7LMAgHkTLeik67arWTVvy+wiDcXpMpcak3W8pm8cdNDbVu96WM=
  matrix:
  - TARGET="webpack@3 html-webpack-plugin@2"
  - TARGET="webpack@4 html-webpack-plugin@3"

matrix:
  exclude:
  - node_js: '4'
    env: TARGET="webpack@4 html-webpack-plugin@3"

  - node_js: '5'
    env: TARGET="webpack@4 html-webpack-plugin@3"

jobs:
  include:
  - stage: deploy
    os: linux
    node_js: node
    env: ""
    script: npm run build
    deploy:
      provider: npm
      email: brunocodutra@gmail.com
      api_key:
        secure: Dht67RlW0DeH6sEg3KJZBhlNc+IJMdUDcAUaVahqhXD1IhXEdsRrAfn1dsbLsbqjhTkBMg37Lq5/QUvLbdmQlvrJ9emu1sbHRAc1JD8RxHAnUbX08i2qJz1UiroJNaJ9gUGH/W8QK3f++pCoza/n/8nPXcy/kB9shBKrGHX+99Rt0xHgfPI5nn/A+KDU9WZ/0/+ITr+83dzwukYJU8lB1id45fv9Avo6c/v219dyfnbKQVYa0o45GsCT3YU3/A2qJa6q1l7I6tNHQ/OBdJ74uarVyUaba+vYxYc3UMJaROvVUErmZmFW1ZEPS5Tu0cHPQKQbvgrWq2ig4eqw7d9PbxCCVjbTFScek4ThMu5OXTPgOhsYoEW+jjQvhz6NS0y6HZUzWR5cPRdA0D5hArHWlZU7jgpVgdSI8cwu+JOBOQtkdzRdVBqhmlq85F7a+qRP58Zj8RgRAZwCBWC9zHNQNHYXO/5SDgtXuxCgh0QF47v81nE4WdNkJ5/tH28vZPNgFqhiVm5w3g6wEXckZNMBNO81OcYs73tAitBHv7R1HhqXGhE7fW1pxzXAAMHl+yVEOzmph/BFoIKQrd7Ag6rTid+/8PCprkMplnaYt8BL9/z5yZ5mzX3tZP5GJKpe32ySNv7VhSqE1b2jbmrHsAsZbKKJ7gk/IsLChidGvYDRReo=
      skip_cleanup: true
      on:
        tags: true
        repo: brunocodutra/webapp-webpack-plugin

  - stage: deploy
    if: type = pull_request
    os: linux
    node_js: node
    env: ""
    script:
    - |
      if [[ -n $(git diff --name-only package-lock.json) ]]
      then
        git config credential.helper "store --file=.git/credentials" || exit $?
        echo "https://${GH_TOKEN}:@github.com" 2> /dev/null > .git/credentials || exit $?
        git remote set-url origin https://github.com/$TRAVIS_REPO_SLUG.git || exit $?
        git add package-lock.json || exit $?
        git commit -m "update package-lock.json" || exit $?
        git push origin HEAD:$TRAVIS_PULL_REQUEST_BRANCH &> /dev/null || exit $?
      fi

before_install:
# package-lock.json was introduced in npm@5
- travis_retry npm install -g npm@latest

install:
- travis_retry npm install
- travis_retry npm install ${TARGET}

before_script:
- git config --global user.name "Travis Bot"
- git config --global user.email "\<\>"

script:
- npm test
