language: node_js
node_js:
- '6'
- '8'
- '10'
- node

os:
- linux
- osx

git:
  depth: 1

env:
  global:
    secure: dHZkfjL0eagnG2UBm4cR3DVFgwyPAc4gr48sBfIPrdee6Zm3uz9ctQcSjTmKtOKKQd0g4BNMTgvpi44JuZX79N67fygWmWMCSKSPInkSsnPJLOVArhC0F+T8Eei19hwaARwFZ++MCmsIUoyFtjLsCaG4tO+6jM1uu/0FXDwL//XcYZefMRLMzGv1j3RLJk9dQfY6InilCEqjvcbMlktNbECJs04GVWSl3RsYTffHYUft+0qrwKKA+eDKLCf3qC5hJ6TLW0foF+fNu16jh/gZtw94b8dhpdEqd9gO0bXz4/jt+sI+ubczio0IX1EdG2WLFJxPQvVNz38Bqof1fBe3hesL64rsr3PFuCPs8kdMIHHkKoDLfRS/K/3+PW25XteHkFOEi8UJg6BB5sw1zDhqKc42gybMDphYOIkUkdoNMbUmFJKJy01pP7jqP45ye0sXL0Gff3YPZGfVry7gK+Bh63esQEaCnPrScrdpB8ycKW+KS+ddv6KWUNdQKSHsEWtikQ505WYHtqZ81XIMP6HXLV3H/lMRfT43NOALUBpauuJ+JXM5f1yl8rSJHY0YoA2CUScmUrgJLQ5KsBdRPq5GXS7TKTuRZ7O7J/yWoAys2ok8BOAiq5sths+oZ7LMAgHkTLeik67arWTVvy+wiDcXpMpcak3W8pm8cdNDbVu96WM=
  matrix:
  - TARGET="webpack@3 html-webpack-plugin@2"
  - TARGET="webpack@4 html-webpack-plugin@3"

jobs:
  include:
  - stage: test
    os: linux
    node_js: node
    env: []
    script: travis_retry npm run coverage
    after_success:
    - travis_retry npm install coveralls
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

  - stage: deploy
    os: linux
    node_js: node
    env: []
    script: skip
    deploy:
      provider: npm
      email: brunocodutra@gmail.com
      api_key:
        secure: AwrQA4iU32lS1A7kjbjq+l+4JwfRBhBohFZ1Y3xUvuHsKJbmziXk0fgKyszfavVL/UpxvSvLFKt31B6+bSzp5uVzcojYQgsHq5PNXNfYq1sVXXIiWsTgKm3j/FU5LvdEvdxqPl8Y6sip/O77UeG6C6w6Z9HzpWJhvbhzro7DxCqycdH4tZD8ubvr+hn2hTmAVOqUuCEPyNGnerOBifEubhoiDnpdVrp5TfGaL5A2lhZk1lPTN0+3ekJDwvQZCRh0xnkksTaVs3R9Fz848HkfwZsyoQuV8NGaO9X6CL6jpT9FQecOsvtS3uwilEWh+LQJFEU8xGevCKzaN68VDDGhL1RSbCV0kxsEpINmg5S0IGf3Ds1GXJvrURriVTwXaeLcKl0DclnogZdkqma8YzmvH5Al+L63GY+RP0OWTlJJLjO00C9B5C4VlDpwCW+YmLEibG55XwCQPq4grFw1IgrLLwNZ7Q7K9vEGkDqnr9lsewEla/zWakRnoJuDo3QUBDsFArpCkR48e5Pupk9AqqB7xOJ24uwUpt2Dbz/SgaL4LCL7SohBkDf2S2MF1BvBTS2kdvf3vKr3fzSD6HpvBSp4wNgOmaGBLV4Y/3zRXWVRi1Zvk6O5s7ffZj8HCZZLQ8ut8fIFMk+8lCRgLf2jHQCQhONayrtxdpfob69zYWxfsLQ=
      on:
        tags: true
        repo: brunocodutra/webapp-webpack-plugin

  - stage: deploy
    if: type = pull_request
    os: linux
    node_js: node
    env: []
    script:
    - |
      if [[ -n $(git diff --name-only package-lock.json) ]]
      then
        git config credential.helper "store --file=.git/credentials" || exit $?
        echo "https://${GH_TOKEN}:@github.com" 2> /dev/null > .git/credentials || exit $?
        git remote set-url origin https://github.com/$TRAVIS_REPO_SLUG.git || exit $?
        git add package-lock.json || exit $?
        git commit -m "update package-lock.json" || exit $?
        git push origin HEAD:$TRAVIS_PULL_REQUEST_BRANCH &> /dev/null || exit $?
      fi

before_install:
# package-lock.json was introduced in npm@5
- travis_retry npm install -g npm@latest

install:
- travis_retry npm install
- travis_retry npm install ${TARGET}

before_script:
- git config --global user.name "Travis Bot"
- git config --global user.email "\<\>"

script:
- travis_retry npm test
